#!/usr/bin/env python3

# makegititnore.py: python program to generate gitignore files
#
# Copyright (C) 2018 Brian van den Broek vanden@gmail.com

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.


import argparse, os, sys

fpath = os.path.join(os.getcwd(), '.gitignore')

# FixMe Do it right (don't want to look up, now)
progName = "makegitignore"
__version__ = "0.2.0"
progRepo = "https://github.com/vanden/makegitignore"


parser = argparse.ArgumentParser(
    description='Generates a .gitignore file',
    epilog='''If no options are specified, all of the various suites are included in the generated .gitignore. If options are specified, only the specified suites are included.'''
)
parser.add_argument('-e', '--emacs', action="store_true", default=False,
                    help='include a suite to ignore various emacs artifacts')
parser.add_argument('-l', '--latex', action="store_true", default=False,
                    help='include a suite to ignore various latex artifacts')
parser.add_argument('-p', '--python', action="store_true", default=False,
                    help='include a suite to ignore various python artifacts')

args = vars(parser.parse_args())

# Needs to come after parsing arguments, lest it be impossible to run the
# --help with a present .gitignore
#
if os.path.isfile(fpath):
    print(f"A .gitignore exists at {fpath} already. Exiting.")
    sys.exit()



if not any(args.values()):
    for key in args.keys():
        args[key] = True


git_ignore_content = [f"""
# This .gitignore file was generated by {progName} v.{__version__}.
# The repositiory for {progName} is {progRepo}.\n
"""]


emacs = """## emacs Stuff
auto/
\#*\#
.\#*

"""


python = """## python stuff
*.pyc
__pycache__/

"""

latex = """## LaTeX Stuff
*.aux
*.log
*.out
*.pdf
*.toc

"""

flags_and_chunks = [
    ('emacs', emacs),
    ('latex', latex),
    ('python', python),
]

for flag, chunk in flags_and_chunks:
    if args[flag]:
        git_ignore_content.append(chunk)


with open(fpath, 'w') as ignoreFile:
    ignoreFile.write('\n'.join(git_ignore_content))
