#!/usr/bin/env python3

# makegititnore.py: python program to generate gitignore files
#
# Copyright (C) 2018 Brian van den Broek vanden@gmail.com

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.


import os, sys

fpath = os.path.join(os.getcwd(), '.gitignore')



if os.path.isfile(fpath):
    print(f"A .gitignore exists at {fpath} already. Exiting.")
    sys.exit()

             
# FixMe Do it right (don't want to look up, now)
progName = "makegitignore"
progVer = "0.1"
progRepo = "https://github.com/vanden/makegitignore"


git_ignore_boilerplate = f"""
# This .gitignore file was generated by {progName} v.{progVer}.
# The repositiory for {progName} is {progRepo}.


## emacs Stuff
auto/
\#*\#
.\#*


## python stuff
*.pyc
__pycache__/


## LaTeX Stuff
*.aux
*.log
*.out
*.pdf
*.toc

"""


with open(fpath, 'w') as ignoreFile:
    ignoreFile.write(git_ignore_boilerplate)
    
